#!/usr/bin/env bash
pfurl --verb POST --raw --http $1/api/v1/cmd --jsonwrapper 'payload' --msg \
        "{   \"action\": \"run\",
            \"meta\":  {
                \"cmd\": \"simpledsapp.py --prefix test- --sleepLength 0 /share/incoming /share/outgoing\",
                \"auid\": \"rudolphpienaar\",
                \"jid\": \"$2\",
                \"threaded\": true,
                \"container\": {
                        \"target\": {
                            \"image\": \"fnndsc/pl-simpledsapp\"
                        }
                }
            }
        }" --quiet --jsonpprintindent 4
